name: mbml
dependencies: 
  - python=3.7
  - numpy 
  - pandas 
  - matplotlib 
  - nltk 
  - scikit-learn 
  - seaborn 
  - jupyter 
  - requests 
  - tqdm
  - nltk
  - black
  - gensim
  - pip
  - clang_osx-64
  - clangxx_osx-64
  - pystan
  - pip:
    - torch
    - pyro-ppl
    - wordcloud==1.7.0
    - "--editable ."